.PHONY: clean
clean:
	-rm $(EXECUTABLE) $(objects)

#gcc -m32 -g -fPIC -shared -o Lib.so Lib.c
#gcc -m32 -g -ldl RunSoSimplePro.c -o RunSoSimplePro
#use the DL(Dynamical Loading)library from /lib/libdl.so.2
#./RunSoSimplePro ./Lib.so foobar i2 i